linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - godot
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

run:
  timeout: 5m